# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.epw_location_schema import EpwLocationSchema  # noqa: F401,E501
from swagger_server import util


class DataHeaderSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, location: EpwLocationSchema=None, data_type: str=None, unit: str=None, analysis_period: str=None):  # noqa: E501
        """DataHeaderSchema - a model defined in Swagger

        :param location: The location of this DataHeaderSchema.  # noqa: E501
        :type location: EpwLocationSchema
        :param data_type: The data_type of this DataHeaderSchema.  # noqa: E501
        :type data_type: str
        :param unit: The unit of this DataHeaderSchema.  # noqa: E501
        :type unit: str
        :param analysis_period: The analysis_period of this DataHeaderSchema.  # noqa: E501
        :type analysis_period: str
        """
        self.swagger_types = {
            'location': EpwLocationSchema,
            'data_type': str,
            'unit': str,
            'analysis_period': str
        }

        self.attribute_map = {
            'location': 'location',
            'data_type': 'data_type',
            'unit': 'unit',
            'analysis_period': 'analysis_period'
        }

        self._location = location
        self._data_type = data_type
        self._unit = unit
        self._analysis_period = analysis_period

    @classmethod
    def from_dict(cls, dikt) -> 'DataHeaderSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataHeaderSchema of this DataHeaderSchema.  # noqa: E501
        :rtype: DataHeaderSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def location(self) -> EpwLocationSchema:
        """Gets the location of this DataHeaderSchema.


        :return: The location of this DataHeaderSchema.
        :rtype: EpwLocationSchema
        """
        return self._location

    @location.setter
    def location(self, location: EpwLocationSchema):
        """Sets the location of this DataHeaderSchema.


        :param location: The location of this DataHeaderSchema.
        :type location: EpwLocationSchema
        """

        self._location = location

    @property
    def data_type(self) -> str:
        """Gets the data_type of this DataHeaderSchema.

        type of data, temperature for example  # noqa: E501

        :return: The data_type of this DataHeaderSchema.
        :rtype: str
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type: str):
        """Sets the data_type of this DataHeaderSchema.

        type of data, temperature for example  # noqa: E501

        :param data_type: The data_type of this DataHeaderSchema.
        :type data_type: str
        """

        self._data_type = data_type

    @property
    def unit(self) -> str:
        """Gets the unit of this DataHeaderSchema.

        data type unit  # noqa: E501

        :return: The unit of this DataHeaderSchema.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit: str):
        """Sets the unit of this DataHeaderSchema.

        data type unit  # noqa: E501

        :param unit: The unit of this DataHeaderSchema.
        :type unit: str
        """

        self._unit = unit

    @property
    def analysis_period(self) -> str:
        """Gets the analysis_period of this DataHeaderSchema.

        a ladybug analysis period string  # noqa: E501

        :return: The analysis_period of this DataHeaderSchema.
        :rtype: str
        """
        return self._analysis_period

    @analysis_period.setter
    def analysis_period(self, analysis_period: str):
        """Sets the analysis_period of this DataHeaderSchema.

        a ladybug analysis period string  # noqa: E501

        :param analysis_period: The analysis_period of this DataHeaderSchema.
        :type analysis_period: str
        """

        self._analysis_period = analysis_period
