# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataTypeSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, value: float=None, _datetime: str=None, standard: str=None, nickname: str=None):  # noqa: E501
        """DataTypeSchema - a model defined in Swagger

        :param value: The value of this DataTypeSchema.  # noqa: E501
        :type value: float
        :param _datetime: The _datetime of this DataTypeSchema.  # noqa: E501
        :type _datetime: str
        :param standard: The standard of this DataTypeSchema.  # noqa: E501
        :type standard: str
        :param nickname: The nickname of this DataTypeSchema.  # noqa: E501
        :type nickname: str
        """
        self.swagger_types = {
            'value': float,
            '_datetime': str,
            'standard': str,
            'nickname': str
        }

        self.attribute_map = {
            'value': 'value',
            '_datetime': 'datetime',
            'standard': 'standard',
            'nickname': 'nickname'
        }

        self._value = value
        self.__datetime = _datetime
        self._standard = standard
        self._nickname = nickname

    @classmethod
    def from_dict(cls, dikt) -> 'DataTypeSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataTypeSchema of this DataTypeSchema.  # noqa: E501
        :rtype: DataTypeSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> float:
        """Gets the value of this DataTypeSchema.


        :return: The value of this DataTypeSchema.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this DataTypeSchema.


        :param value: The value of this DataTypeSchema.
        :type value: float
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def _datetime(self) -> str:
        """Gets the _datetime of this DataTypeSchema.


        :return: The _datetime of this DataTypeSchema.
        :rtype: str
        """
        return self.__datetime

    @_datetime.setter
    def _datetime(self, _datetime: str):
        """Sets the _datetime of this DataTypeSchema.


        :param _datetime: The _datetime of this DataTypeSchema.
        :type _datetime: str
        """
        if _datetime is None:
            raise ValueError("Invalid value for `_datetime`, must not be `None`")  # noqa: E501

        self.__datetime = _datetime

    @property
    def standard(self) -> str:
        """Gets the standard of this DataTypeSchema.


        :return: The standard of this DataTypeSchema.
        :rtype: str
        """
        return self._standard

    @standard.setter
    def standard(self, standard: str):
        """Sets the standard of this DataTypeSchema.


        :param standard: The standard of this DataTypeSchema.
        :type standard: str
        """
        allowed_values = ["SI", "IP"]  # noqa: E501
        if standard not in allowed_values:
            raise ValueError(
                "Invalid value for `standard` ({0}), must be one of {1}"
                .format(standard, allowed_values)
            )

        self._standard = standard

    @property
    def nickname(self) -> str:
        """Gets the nickname of this DataTypeSchema.


        :return: The nickname of this DataTypeSchema.
        :rtype: str
        """
        return self._nickname

    @nickname.setter
    def nickname(self, nickname: str):
        """Sets the nickname of this DataTypeSchema.


        :param nickname: The nickname of this DataTypeSchema.
        :type nickname: str
        """
        if nickname is None:
            raise ValueError("Invalid value for `nickname`, must not be `None`")  # noqa: E501

        self._nickname = nickname
