# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ErrorModelSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, code: int=None):  # noqa: E501
        """ErrorModelSchema - a model defined in Swagger

        :param message: The message of this ErrorModelSchema.  # noqa: E501
        :type message: str
        :param code: The code of this ErrorModelSchema.  # noqa: E501
        :type code: int
        """
        self.swagger_types = {
            'message': str,
            'code': int
        }

        self.attribute_map = {
            'message': 'message',
            'code': 'code'
        }

        self._message = message
        self._code = code

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorModelSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorModelSchema of this ErrorModelSchema.  # noqa: E501
        :rtype: ErrorModelSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this ErrorModelSchema.

        A helpful error message  # noqa: E501

        :return: The message of this ErrorModelSchema.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ErrorModelSchema.

        A helpful error message  # noqa: E501

        :param message: The message of this ErrorModelSchema.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def code(self) -> int:
        """Gets the code of this ErrorModelSchema.


        :return: The code of this ErrorModelSchema.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this ErrorModelSchema.


        :param code: The code of this ErrorModelSchema.
        :type code: int
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501
        if code is not None and code > 600:  # noqa: E501
            raise ValueError("Invalid value for `code`, must be a value less than or equal to `600`")  # noqa: E501
        if code is not None and code < 100:  # noqa: E501
            raise ValueError("Invalid value for `code`, must be a value greater than or equal to `100`")  # noqa: E501

        self._code = code
